// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6-4o5tWuJ3K7D0RF6keTrMDS-GkbnLs',
    appId: '1:454660273096:web:6a3cbb53582d6db21f46fd',
    messagingSenderId: '454660273096',
    projectId: 'mahad-5fc63',
    authDomain: 'mahad-5fc63.firebaseapp.com',
    storageBucket: 'mahad-5fc63.firebasestorage.app',
    measurementId: 'G-D222C1J5S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbqSvMWTY7vEsSoqbCC344bhg1e8sHV0',
    appId: '1:454660273096:android:f63aa01f2272e0e61f46fd',
    messagingSenderId: '454660273096',
    projectId: 'mahad-5fc63',
    storageBucket: 'mahad-5fc63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL6DxV_lMHqlEnzMu1QLN8BlpY8_k2jbs',
    appId: '1:454660273096:ios:43d1be145add4ae81f46fd',
    messagingSenderId: '454660273096',
    projectId: 'mahad-5fc63',
    storageBucket: 'mahad-5fc63.firebasestorage.app',
    iosBundleId: 'com.mujahid.mahad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL6DxV_lMHqlEnzMu1QLN8BlpY8_k2jbs',
    appId: '1:454660273096:ios:43d1be145add4ae81f46fd',
    messagingSenderId: '454660273096',
    projectId: 'mahad-5fc63',
    storageBucket: 'mahad-5fc63.firebasestorage.app',
    iosBundleId: 'com.mujahid.mahad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE6-4o5tWuJ3K7D0RF6keTrMDS-GkbnLs',
    appId: '1:454660273096:web:d6b29102277186e01f46fd',
    messagingSenderId: '454660273096',
    projectId: 'mahad-5fc63',
    authDomain: 'mahad-5fc63.firebaseapp.com',
    storageBucket: 'mahad-5fc63.firebasestorage.app',
    measurementId: 'G-EH1Z9NC54J',
  );
}
